#!/usr/bin/bash

scripts/overview "$1"

if [ "$1" == "--once" ]; then
  exit 0
else
  socat -u UNIX-CONNECT:${XDG_RUNTIME_DIR}/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r line; do
    scripts/overview "$1"
  done
fi