-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        col = {
            active_border = {
                colors = { "rgba(0DB7D4FF)", "rgba(7AA2F7FF)", "rgba(9778D0FF)" },
                angle = 45
	    },
            inactive_border = "rgba(04404aaa)",
        },
    },
})

