-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XMODIFIERS", "@im=ibus")
hl.env("GTK_IM_MODULE", "ibus")
hl.env("QT_IM_MODULE", "ibus")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")
