-- Wallpaper
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Status bar
--exec-once = waybar
--exec-once = eww daemon && eww open winbar &

-- Noctalia dock

-- Language Switch

-- Core components (authentication, lock screen, notification daemon)

-- Clipboard history

-- Cursor and Touchpad gestures

hl.on("hyprland.start", function()
    hl.exec_cmd("swaybg -i ~/.config/eww/images/wallpaper/wallpaper")
    hl.exec_cmd("eww daemon && eww open bar && eww open bottomline")
    hl.exec_cmd("~/.config/eww/scripts/get_open_icons &")
    hl.exec_cmd("noctalia")
    hl.exec_cmd("ibus-daemon --xim -d -r")
    hl.exec_cmd("ibus engine xkb:us::eng")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("/usr/bin/gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &")
    hl.exec_cmd("dunst &")
    hl.exec_cmd("swayidle -w timeout 300 'qs -c noctalia-shell ipc call lockScreen lock' before-sleep 'qs -c noctalia-shell ipc call lockScreen lock' &")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
    hl.exec_cmd("libinput-gestures-setup start")
    hl.exec_cmd("sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
