general {
    before_sleep_cmd = noctalia msg session lock
    ignore_dbus_inhibit = false     # respect Wayland/dbus idle-inhibit requests (Firefox, mpv, Steam, etc.)
    ignore_systemd_inhibit = false  # respect `systemd-inhibit --what=idle`
}

listener {
    timeout = 3000
    on-timeout = noctalia msg session lock
}
