-- This file contains general customization options 
-- For Environment variables see env.conf
-- For Keybinds variables see keybinds.conf 
-- For Auto-run stuff see execs.conf
--autogenerated = 1

-- I haven't updated yet but prepared
-- source=~/.config/hypr/env.conf

-- Monitor: reserve space for eww bar
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "eDP-1",
    addreserved = { top = 1, bottom = 1, left = 61, right = 1 },
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60",
    position = "1920x0",
    scale = "1",
    mirror = "eDP-1",
})

--################### Core components (authentication, idle daemon and stuff) ##############
-- Source: ~/.config/hypr/execs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("execs")

--############################ Keybinds ############################
-- Source: ~/.config/hypr/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("keybinds")

--############################# Input ##############################

hl.curve("md3_standard", { type = "bezier", points = { { 0.2, 0.0 }, { 0, 1.0 } } })
hl.curve("md3_decel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("md3_accel", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("hyprnostretch", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.0 } } })
hl.curve("win10", { type = "bezier", points = { { 0, 0 }, { 0, 1 } } })
hl.curve("gnome", { type = "bezier", points = { { 0, 0.85 }, { 0.3, 1 } } })
hl.curve("funky", { type = "bezier", points = { { 0.46, 0.35 }, { -0.2, 1.2 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 2,
    bezier = "md3_decel",
    style = "slide",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 0.0000001,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 4,
    bezier = "md3_decel",
    style = "slidevert",
})

hl.window_rule({
    match = {
        class = "^(steam)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(guifetch)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "title:^(Open File)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "title:^(Open Folder)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "title:^(Save As)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "title:^(Library)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^com.github.hluk.copyq$",
    },
    float = true,
})

hl.window_rule({
    match = {
        float = 1,
    },
    rounding = 10,
})

hl.layer_rule({
    match = { namespace = "gtk-layer-shell" },
    blur = true,
    -- TODO: manual review — unmapped layer rule: "ignorezero"
})

hl.layer_rule({
    match = { namespace = "waybar" },
    blur = true,
    -- TODO: manual review — unmapped layer rule: "ignorezero"
})

-- TODO: manual review — plugin section ''. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
  hyprbars { ... }
  borders-plus-plus { ... }
]]

-- Source: ~/.config/hypr/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("colors")
hl.config({
    input = {
        -- Mouse
        -- accel_profile = adaptive
        force_no_accel = false,
        --sensitivity = 0
        -- osu
        -- force_no_accel = true
        -- sensitivity = -0.23 
        -- Keyboard
        kb_layout = "us",
        follow_mouse = 1,
        numlock_by_default = true,
        touchpad = {
            natural_scroll = true,
            disable_while_typing = true,
            clickfinger_behavior = true,
            scroll_factor = 0.7,
        },
        scroll_method = "2fg",
    },
    gestures = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        workspace_swipe = true,
        workspace_swipe_distance = "1000px",
        workspace_swipe_fingers = 4,
        workspace_swipe_cancel_ratio = 0.05,
        workspace_swipe_min_speed_to_force = 5,
        workspace_swipe_create_new = true,
    },
    general = {
        -- Gaps and border
        gaps_in = 4,
        gaps_out = 7,
        border_size = 2,
        -- Fallback colors
        col = {
            active_border = { colors = { "rgba(0DB7D4FF)", "rgba(7AA2F7FF)", "rgba(9778D0FF)" }, angle = 45 },
            inactive_border = "rgba(04404aaa)",
        },
        -- Functionality
        -- resize_on_border = true
        layout = "dwindle",
    },
    decoration = {
        -- Blur rules
        -- blurls=gtk-layer-shell
        rounding = 17,
        -- Blur
        blur = true,
        blur_size = 7,
        blur_passes = 4,
        blur_new_optimizations = true,
        blur_ignore_opacity = false,
        --blur_xray = true
        -- Shadow
        drop_shadow = false,
        shadow_range = 30,
        shadow_render_power = 3,
        col = {
            shadow = "rgba(01010166)",
        },
        -- Opacity
        -- Shader
        -- screen_shader = ~/.config/hypr/shaders/nothing.frag
        -- Dim
        dim_inactive = false,
        dim_strength = 0.1,
        dim_special = 0,
        --screen_shader = ~/.config/hypr/shaders/drugs.frag
        --screen_shader = ~/.config/hypr/shaders/crt.frag
    },
    animations = {
        enabled = true,
        -- Animation curves
        -- Animation configs
    },
    misc = {
        vfr = 1,
        vrr = 0,
        focus_on_activate = true,
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
        --suppress_portal_warnings = true
        enable_swallow = true,
    },
    debug = {
        --overlay = true
        --damage_tracking=0
    },
    dwindle = {
        preserve_split = true, -- you probably want this
        --no_gaps_when_only = true
    },
    -- Efficiency
    --general {
    --	gaps_in = 0
    --    gaps_out = 0
    --	border_size = 2
    --}
    --decoration {
    --	rounding = 0
    --}
    --monitor=eDP-1, addreserved, 32, 0, 0, 0
    --####### Window rules ########
    --windowrule = float, ^(firefox)$
    --windowrule = opacity 0.9 override 0.9 override, ^(firefox)$
    -- Dialogs
    --####### Layer rules ########
    -- Dynamic colors are written here
})

