--######################### Language ############################
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind("SUPERSHIFT + V", hl.dsp.exec_cmd("ibus engine Bamboo::Us"))
hl.bind("SUPERSHIFT + E", hl.dsp.exec_cmd("ibus engine xkb:us::eng"))

--################### It just works™ keybinds ###################
-- Volume
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/.config/eww/scripts/volume osd &"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/.config/eww/scripts/volume osd &"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("~/.config/eww/scripts/volume osd &"), { locked = true })

-- Brightness
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("light -A 3 && ~/.config/eww/scripts/brightness osd &"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("light -U 3 && ~/.config/eww/scripts/brightness osd &"), { locked = true, repeating = true })

--####################################### Keybinds ########################################
-- Apps: just normal apps
hl.bind("SUPER + C", hl.dsp.exec_cmd("code --password-store=gnome --enable-features=UseOzonePlatform --ozone-platform=wayland"))
hl.bind("CONTROLSHIFTALT + Y", hl.dsp.exec_cmd("yuzu"))
hl.bind("SUPER + T", hl.dsp.exec_cmd("foot --override shell=fish"))
hl.bind("SUPERALT + T", hl.dsp.exec_cmd("wezterm"))
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))
hl.bind("SUPER + E", hl.dsp.exec_cmd("nautilus --new-window"))
hl.bind("SUPER + W", hl.dsp.exec_cmd("firefox"))
hl.bind("CONTROLSUPERALT + E", hl.dsp.exec_cmd("/usr/bin/microsoft-edge-stable --password-store=gnome --enable-features=UseOzonePlatform --ozone-platform=wayland --gtk-version=4"))
hl.bind("SUPER + X", hl.dsp.exec_cmd("gnome-text-editor --new-window"))
hl.bind("SUPERSHIFT + W", hl.dsp.exec_cmd("wps"))

--Apps: Settings and config
hl.bind("SUPER + I", hl.dsp.exec_cmd("gnome-control-center"))
hl.bind("CONTROLSUPER + V", hl.dsp.exec_cmd("pavucontrol"))
hl.bind("CONTROLSHIFT + Escape", hl.dsp.exec_cmd("gnome-system-monitor"))
hl.bind("CONTROLALTSHIFT + Escape", hl.dsp.exec_cmd("foot -T 'btop' btop"))
hl.bind("SUPERSHIFT + I", hl.dsp.exec_cmd("~/.local/bin/guifetch"))

-- Actions 
hl.bind("SUPERSHIFT + Period", hl.dsp.exec_cmd("pkill wofi || wofi-emoji"))
hl.bind("SUPER + Period", hl.dsp.exec_cmd("pkill fuzzel || ~/.local/bin/fuzzel-emoji"))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPERALT + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SHIFTSUPERALT + Q", hl.dsp.exec_cmd("hyprctl kill"))
hl.bind("CONTROLALT + Delete", hl.dsp.exec_cmd("pkill wlogout || wlogout -p layer-shell"))
hl.bind("CONTROLSHIFTALTSUPER + Delete", hl.dsp.exec_cmd("systemctl poweroff"))

-- Screenshot, Record, OCR (Optical Character Recognition), Color picker, Clipboard history
hl.bind("SUPERSHIFT + D", hl.dsp.exec_cmd("~/.local/bin/rubyshot | wl-copy"))
hl.bind("SUPERSHIFTALT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -"))
hl.bind("Print", hl.dsp.exec_cmd("grim - | wl-copy"), { locked = true })
hl.bind("SUPERSHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"))
hl.bind("SUPERALT + R", hl.dsp.exec_cmd("~/.local/bin/record-script.sh"))
hl.bind("CONTROLALT + R", hl.dsp.exec_cmd("~/.local/bin/record-script.sh --sound"))
hl.bind("SUPERSHIFTALT + R", hl.dsp.exec_cmd("~/.local/bin/record-script-fullscreen.sh"))
hl.bind("CONTROLSUPERSHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" \"tmp.png\" && tesseract \"tmp.png\" - | wl-copy && rm \"tmp.png\""))
hl.bind("SUPERSHIFT + T", hl.dsp.exec_cmd("grim -g \"$(slurp)\" \"tmp.png\" && tesseract \"tmp.png\" - | wl-copy && rm \"tmp.png\""))
hl.bind("SUPERSHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"))
hl.bind("SUPER + B", hl.dsp.exec_cmd("copyq menu"))
hl.bind("SUPER + V", hl.dsp.exec_cmd("pkill fuzzel || cliphist list | fuzzel --no-fuzzy --icon-theme=candy-icons --background-color=1D1D27ee --text-color=cdd6f4ff --match-color=AC16C7FF --border-width=3 --border-radius=10 --border-color=8701E7FF\t --selection-color=585b70ff --selection-text-color=cdd6f4ff --selection-match-color=AC16C7FF --font=\"Rubik\"  --prompt=\"   \" --dmenu | cliphist decode | wl-copy"))
-- Media
hl.bind("SUPERSHIFT + N", hl.dsp.exec_cmd("playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\"`"))
hl.bind("SUPERSHIFT + B", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("SUPERSHIFT + P", hl.dsp.exec_cmd("playerctl play-pause"))
--Lock screen  |  blur: --effect-blur=20x20
hl.bind("SUPER + L", hl.dsp.exec_cmd("~/.local/bin/lock.sh"))
hl.bind("SUPERSHIFT + L", hl.dsp.exec_cmd("~/.local/bin/lock.sh"))
hl.bind("SUPERSHIFT + L", hl.dsp.exec_cmd("sleep 0.1 && systemctl suspend"), { locked = true })
-- App launcher
hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-overview.sh --keypress &"), { release = true })
hl.bind("SUPER + Slash", hl.dsp.exec_cmd("pkill fuzzel || fuzzel --icon-theme=candy-icons --background-color=1D1D27ee --text-color=cdd6f4ff --match-color=AC16C7FF --border-width=3 --border-radius=10 --border-color=8701E7FF\t --selection-color=585b70ff --selection-text-color=cdd6f4ff --selection-match-color=AC16C7FF --font=\"Rubik\"  --prompt=\"    \""))
--bindr = SUPER, SUPER_L, exec, pkill rofi || rofi -show drun

--################################ eww keybinds ################################
hl.bind("CONTROLSUPER + R", hl.dsp.exec_cmd("pkill eww && eww daemon && eww open bar && eww open bg-decor"), { release = true })
hl.bind("SUPER + Tab", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-overview.sh"))
hl.bind("SUPER + O", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-osettings.sh --keypress"))
hl.bind("CONTROLSUPER + O", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-osettings.sh --keypress"))
hl.bind("SUPER + M", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-bottombar.sh"))
hl.bind("SUPER + N", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-onotify.sh --keypress"))
hl.bind("SUPER + Comma", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-themer.sh"))
hl.bind("SUPER + D", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-dash.sh --keypress"))
hl.bind("SUPER + A", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-dashfs.sh"))
hl.bind("SUPER + G", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-wingamebar.sh"))

hl.bind("CONTROLSUPER + Tab", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-compactmode.sh"))
hl.bind("SUPERALT + W", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle-winmode.sh"))

--########################### Keybinds for Hyprland ############################
-- Swap windows
hl.bind("SUPERSHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPERSHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPERSHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPERSHIFT + down", hl.dsp.window.move({ direction = "d" }))
-- Move focus
hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + BracketLeft", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + BracketRight", hl.dsp.focus({ direction = "right" }))
-- Window title
hl.bind("SUPER + left", hl.dsp.exec_cmd("eww update rev_center_ws=false"))
hl.bind("SUPER + right", hl.dsp.exec_cmd("eww update rev_center_ws=false"))
hl.bind("SUPER + up", hl.dsp.exec_cmd("eww update rev_center_ws=false"))
hl.bind("SUPER + down", hl.dsp.exec_cmd("eww update rev_center_ws=false"))
hl.bind("SUPER + BracketLeft", hl.dsp.exec_cmd("eww update rev_center_ws=false"))
hl.bind("SUPER + BracketRight", hl.dsp.exec_cmd("eww update rev_center_ws=false"))
hl.bind("ALT + Tab", hl.dsp.exec_cmd("eww update rev_center_ws=false"))

-- Workspace, window, tab switch with keyboard
hl.bind("CONTROLSUPER + right", hl.dsp.focus({ workspace = "+1" }))
hl.bind("CONTROLSUPER + left", hl.dsp.focus({ workspace = -1 }))
hl.bind("CONTROLSUPER + BracketLeft", hl.dsp.focus({ workspace = -1 }))
hl.bind("CONTROLSUPER + BracketRight", hl.dsp.focus({ workspace = "+1" }))
hl.bind("CONTROLSUPER + up", hl.dsp.focus({ workspace = -5 }))
hl.bind("CONTROLSUPER + down", hl.dsp.focus({ workspace = "+5" }))
hl.bind("SUPER + Page_Down", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + Page_Up", hl.dsp.focus({ workspace = -1 }))
hl.bind("CONTROLSUPER + Page_Down", hl.dsp.focus({ workspace = "+1" }))
hl.bind("CONTROLSUPER + Page_Up", hl.dsp.focus({ workspace = -1 }))
hl.bind("SUPERSHIFT + Page_Down", hl.dsp.window.move({ workspace = "+1" }))
hl.bind("SUPERSHIFT + Page_Up", hl.dsp.window.move({ workspace = -1 }))
hl.bind("CONTROLSUPERSHIFT + Right", hl.dsp.window.move({ workspace = "+1" }))
hl.bind("CONTROLSUPERSHIFT + Left", hl.dsp.window.move({ workspace = -1 }))
hl.bind("SUPERSHIFT + mouse_down", hl.dsp.window.move({ workspace = -1 }))
hl.bind("SUPERSHIFT + mouse_up", hl.dsp.window.move({ workspace = "+1" }))

-- Show workspaces module
hl.bind("CONTROLSUPER + right", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("CONTROLSUPER + left", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("CONTROLSUPER + BracketLeft", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("CONTROLSUPER + BracketRight", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("CONTROLSUPER + up", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("CONTROLSUPER + down", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("SUPER + Page_Down", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("SUPER + Page_Up", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("CONTROLSUPER + Page_Down", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("CONTROLSUPER + Page_Up", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("SUPERSHIFT + Page_Down", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("SUPERSHIFT + Page_Up", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("CONTROLSUPERSHIFT + Right", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("CONTROLSUPERSHIFT + Left", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("SUPERSHIFT + mouse_down", hl.dsp.exec_cmd("eww update rev_center_ws=true"))
hl.bind("SUPERSHIFT + mouse_up", hl.dsp.exec_cmd("eww update rev_center_ws=true"))

-- Window split ratio
hl.bind("SUPER + Minus", hl.dsp.layout("splitratio -0.1"), { repeating = true })
hl.bind("SUPER + Equal", hl.dsp.layout("splitratio 0.1"), { repeating = true })
hl.bind("SUPER + Semicolon", hl.dsp.layout("splitratio -0.1"), { repeating = true })
hl.bind("SUPER + Apostrophe", hl.dsp.layout("splitratio 0.1"), { repeating = true })
-- Fullscreen
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
-- Switching
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special(""))
hl.bind("CONTROLSUPER + S", hl.dsp.workspace.toggle_special(""))
hl.bind("ALT + Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind("ALT + Tab", hl.dsp.window.bring_to_top())
-- Move window to workspace Super + Alt + [0-9]
hl.bind("SUPER + ALT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind("SUPER + ALT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind("SUPER + ALT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind("SUPER + ALT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind("SUPER + ALT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind("SUPER + ALT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind("SUPER + ALT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind("SUPER + ALT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind("SUPER + ALT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind("SUPER + ALT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))
hl.bind("CONTROLSHIFTSUPER + Up", hl.dsp.window.move({ workspace = "special", follow = false }))
hl.bind("SUPERALT + S", hl.dsp.window.move({ workspace = "special", follow = false }))
-- Scroll through existing workspaces with (Control) + Super + scroll
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = -1 }))
hl.bind("CONTROLSUPER + mouse_up", hl.dsp.focus({ workspace = "+1" }))
hl.bind("CONTROLSUPER + mouse_down", hl.dsp.focus({ workspace = -1 }))
-- Move/resize windows with Super + LMB/RMB and dragging
hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())
hl.bind("SUPER + mouse:274", hl.dsp.window.drag())
hl.bind("SUPER + Z", hl.dsp.window.drag())
hl.bind("CONTROLSUPER + Backslash", hl.dsp.window.resize({ x = 640, y = 480 }))

-- trying vim-like stuff
hl.bind("SUPER_ALT + I", hl.dsp.exec_cmd("wtype -k Up"), { repeating = true })
hl.bind("SUPER_ALT + K", hl.dsp.exec_cmd("wtype -P Down"), { repeating = true })
hl.bind("SUPER_ALT + J", hl.dsp.exec_cmd("wtype -P Left"), { repeating = true })
hl.bind("SUPER_ALT + L", hl.dsp.exec_cmd("wtype -P Right"), { repeating = true })

